formation_costmap:
  # Die beiden hier muss ich nicht variabel machen, andere m√ºssen sich danach richten, woher sie die Infos bekommen
  # formation_footprint_topic_name: formation_footprint
  # formation_centre_topic_name: formation_centre
  formation_robots:
    robot0:
      master: true
      namespace: /robot0_ns
      robot_outline: [[0.506,-0.32],[0.506,0.32],[-0.454,0.32],[-0.454,-0.32]]
      robot_pose_topic: amcl_pose 
    robot1:
      namespace: /robot1_ns
      robot_outline: [[0.506,-0.32],[0.506,0.32],[-0.454,0.32],[-0.454,-0.32]]
      robot_pose_topic: amcl_pose
    robot2:
      namespace: /robot2_ns
      robot_outline: [[0.506,-0.32],[0.506,0.32],[-0.454,0.32],[-0.454,-0.32]]
      robot_pose_topic: amcl_pose 