planners:
  - name: 'FormationPathPlanner'
    type: 'global_planner/FormationPathPlanner'
  # - name: 'RelaxedAStar'
  #   type: 'global_planner/RelaxedAStar'
  # - name: 'AdvancedAStar'
  #   type: 'global_planner/AdvancedAStar'


planner_patience: 10.0

FormationPathPlanner:
  # The default tolerance that is used if the tolerance of the received goal is not valid.
  # Default: 0.2
  default_tolerance: 0.2

  used_formation_planner: SplinedRelaxedAStar

  # reconfiguration_start: 50
  # reconfiguration_end: 150

  formation_config:
    robot0:
      namespace: /robot0_ns
      master: true
      robot_outline: [[0.506,-0.32],[0.506,0.32],[-0.454,0.32],[-0.454,-0.32]]

      # This is only used in the generation of the footprint.
      # Normally the footprint is generated in a costmap layer. 
      # Later this functionality will be exported into a costmap layer
      robot_pose_topic: amcl_pose 
    robot1:
      namespace: /robot1_ns
      offset: [0.0, -1.0] # Defines distance from master robot
      # reconfig_offset: [-1.0, 0.7] # Defines the distance from the master after reconfiguration
      robot_outline: [[0.506,-0.32],[0.506,0.32],[-0.454,0.32],[-0.454,-0.32]]

      # This is only used in the generation of the footprint.
      # Normally the footprint is generated in a costmap layer. 
      # Later this functionality will be exported into a costmap layer
      robot_pose_topic: amcl_pose

  formation_path_planner:
    # This planner is used to create the initial path from where all robots have to offset their own path
    SplinedRelaxedAStar:
      # The default tolerance that is used if the tolerance of the received goal is not valid.
      # Default: 0.2
      default_tolerance: 0.2
      # How many of the neighbor cells should be used. Options:
      # 4 - This means the cells in the north, south, west, east direction are used
      # 8 - This means all cells around (also the diagonal ones) are used
      # Default: 8
      neighbor_type: 8
      # Threshold for the costmap values that define if a cell is free or not.
      # This image: http://wiki.ros.org/costmap_2d?action=AttachFile&do=get&target=costmapspec.png explains the cell cost values.
      # Value 0 means the farthest away from the wall. Value 254 defines a cell where an obstacle is located.
      # The greater this value will be defined the closer the global path will be planed next to walls.
      # Default: 0
      free_cell_threshold: 0
      # Distance that is added from the start point of the Relaxed A Star in the direction of the start orientation.
      # This should help no creating splines that instantly make a curve
      start_straight_distance: 1.0
      # Distance that is subtracted from the end point of the Relaxed A Star in the direction of the end orientation.
      # This should help no creating splines that instantly make a curve before the end
      end_straight_distance: 1.0
      # Every nth cell the cell of the RelaxedAStar planner will be used to generate splines
      # Every nth cell will act as a control point
      control_point_distance: 80
      # This value defines how many points should be inserted into the plan from one spline.
      # F.e. control_point_distance = 50. With 0.05m per cell the control points are spaced every 2.5m.
      # With a planning_points_per_spline value of 20 this would generate 30 points into the plan that are in between two control points.
      # So roughly every 0.125m
      planning_points_per_spline: 100
      # Minimal radius of a curve the formation can drive in m.
      # This value will also be checked when the formation shape is known and the minimal radius of a curve will be calculated.
      # Whichever radius is bigger will be selected for creating the splines
      minimal_curve_radius: 1.7

RelaxedAStar:
  # The default tolerance that is used if the tolerance of the received goal is not valid.
  # Default: 0.2
  default_tolerance: 0.2
  # How many of the neighbor cells should be used. Options:
  # 4 - This means the cells in the north, south, west, east direction are used
  # 8 - This means all cells around (also the diagonal ones) are used
  # Default: 8
  neighbor_type: 8
  # Threshold for the costmap values that define if a cell is free or not.
  # This image: http://wiki.ros.org/costmap_2d?action=AttachFile&do=get&target=costmapspec.png explains the cell cost values.
  # Value 0 means the farthest away from the wall. Value 254 defines a cell where an obstacle is located.
  # The greater this value will be defined the closer the global path will be planed next to walls.
  # Default: 0
  free_cell_threshold: 0 

  # This value specifies different modes for declaring new cells as free and usable cells that will get added to the open list.
  # 0 - This mode only uses the g_scores of the cells. If the score of the selected cell is infinity, the cell will be pushed into the open list
  # 1 - This mode uses the same selection as mode 0. Additionally the curves get analyzed to have a maximal curvature. See: minimal_curve_radius parameter
  # Default: 0
  free_neighbor_mode: 0

  # This parameter is used together with the mode 1 of the free_neighbor_mode.
  # This parameter defines the maximal curvature the global plan should contain during a curve.
  # This parameter is specified in degree.
  # Default: 20
  maximal_curvature: 40

  # This parameter defines the distance between the two points that are used for calculating the curvature of the path.
  # For example 1 uses the current cell and the cell that the global planner wants to expand to or place in the open set.
  # 4 uses the following setup |x|3|2|C|F where F is future cell, C is current cell where the neighbors are inspcted and x is the fourth cell.
  # Notice that the resulting angle heavily depends on this value!
  # If this parameter is 1 then with neighbor_type_=8 the resulting value will be 0 or a multiple of 45째.
  # So if the maximal_curvature_ is smaller than 45째 the robot would not be able to turn.
  # Default: 4
  curvature_calculation_cell_distance: 6

AdvancedAStar:
  # The default tolerance that is used if the tolerance of the received goal is not valid.
  # Default: 0.2
  default_tolerance: 0.2
  # How many of the neighbor cells should be used. Options:
  # 4 - This means the cells in the north, south, west, east direction are used
  # 8 - This means all cells around (also the diagonal ones) are used
  # Default: 8
  neighbor_type: 8
  # Threshold for the costmap values that define if a cell is free or not.
  # This image: http://wiki.ros.org/costmap_2d?action=AttachFile&do=get&target=costmapspec.png explains the cell cost values.
  # Value 0 means the farthest away from the wall. Value 254 defines a cell where an obstacle is located.
  # The greater this value will be defined the closer the global path will be planed next to walls.
  # Default: 0
  free_cell_threashold: 0 

  # This value specifies different modes for declaring new cells as free and usable cells that will get added to the open list.
  # 0 - This mode only uses the g_scores of the cells. If the score of the selected cell is infinity, the cell will be pushed into the open list
  # 1 - This mode uses the same selection as mode 0. Additionally the curves get analyzed to have a maximal curvature. See: minimal_curve_radius parameter
  # Default: 0
  free_neighbor_mode: 1

  # This parameter is used together with the mode 1 of the free_neighbor_mode.
  # This parameter defines the maximal curvature the global plan should contain during a curve.
  # This parameter is specified in degree.
  # Default: 20
  maximal_curvature: 20

  # This parameter defines the distance between the two points that are used for calculating the curvature of the path.
  # For example 1 uses the current cell and the cell that the global planner wants to expand to or place in the open set.
  # 4 uses the following setup |x|3|2|C|F where F is future cell, C is current cell where the neighbors are inspcted and x is the fourth cell.
  # Notice that the resulting angle heavily depends on this value!
  # If this parameter is 1 then with neighbor_type_=8 the resulting value will be 0 or a multiple of 45째.
  # So if the maximal_curvature_ is smaller than 45째 the robot would not be able to turn.
  # Default: 4
  curvature_calculation_cell_distance: 6

# GlobalPlanner:
#   allow_unknown: true
#   default_tolerance: 0.0
#   visualize_potential: true
#   #######Set parameters#############
#   use_dijkstra: true #1#true #If true, use dijkstra's algorithm. Otherwise, A*. 
#   use_quadratic: true #2#true #If true, use the quadratic approximation of the ##potential##. Otherwise, use a simpler calculation. 
#   use_grid_path: false #3#false #If true, create a path that follows the grid boundaries. Otherwise, use a gradient descent method. 
#   old_navfn_behaviour: false
#   lethal_cost: 253
#   neutral_cost: 66
#   cost_factor: 0.55
#   publish_potential: true
#   orientation_mode: 0.0
#   orientation_window_size: 1.0

# SBPLLatticePlanner:
#   planner_type: 'ARAPlanner'
#   allocated_time: 3.0 # default: 10.0 #The amount of time given to the planner to find a solution.
#   initial_epsilon: 3.0 # The larger this value is the faster the search tends to find a solution
#   environment_type: 'XYThetaLattice' # The only environment supported
#   forward_search: false # default is false
#   # NOTE: param 'primitive_filename'. This needs to be set to the path to 'ceres_navigation/mprim/ceres_5cm.mprim'
#   # You may put it in the mprim.yaml file, which is ignored by git, so everybody can setup his own path.
#   nominalvel_mpersecs: 0.4
#   timetoturn45degsinplace_secs: 0.3